### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by iam-veeramalla**

### CODE REVIEW

**Comment by dima-k144** [comment]
Thank you.

**Comment by ghost** [comment]
Lol. I do not know grammar
DAMN MY ENGLISH

**Comment by ghost** [comment]
Hey Jeff, Hope so you got my request to access Penetration Coin. After this access dude I want you to monitor the pull requests. Thanks.

**Comment by dima-k144** [comment]
OK, i will monitor them.

**Comment by ghost** [comment]
:-)
;-)

**Pull request merged**
